config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "dashboard#index"
    get '/users/sign_out',:to => 'devise/sessions#destroy'
    get '/users/sign_in', :to => 'devise/sessions#new'
    resources :customers, only: [:index, :new, :create, :show]
    resources :carts, only: [:index,:new,:show, :create,:errors, :search]
    get 'errors',  to: 'carts#errors', as: :error
    get 'search', to: 'carts#search', as: :search
end

app/models/Warranty_Search.rb
module Warranty
  # attr :warranty
  def warrantAlist
    @warrantyA = Array(1...440383)
  end
  def warrantBlist
    @warrantyB = Array(320458...383845)
  end
end
class Warranty_Search < ApplicationRecord
  include Warranty
  def search(cart_number)
    case cart_number
      when @warrantyA.warrantAlist.include?(cart_number) == true
            @cart = Cart.new(carts_params)
      when @warrantyA.warrantBlist.include?(cart_number) == true
            @cart = Cart.new(carts_params)
      when @warrantyA.warrantAlist.include?(cart_number) == false
           render error_path
      when @warrantyA.warrantBlist.include?(cart_number) == false
          render error_path
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # has_many :carts
end

app/models/customer_search_term.rb
class CustomerSearchTerm
  attr_reader :where_clause, :where_args, :order
  def initialize(search_term)
    search_term = search_term.downcase
    @where_clause = ""
    @where_args = {}
    if search_term =~ /@/
      build_for_email_search(search_term)
    else
      build_for_name_search(search_term)
    end
  end

private

  def build_for_name_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(search_term)

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(search_term)

    @order = "last_name asc"
  end

  def starts_with(search_term)
    search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

  def extract_name(email)
    email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
  end

  def build_for_email_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(extract_name(search_term))

    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(extract_name(search_term))

    @where_clause << " OR #{case_insensitive_search(:email)}"
    @where_args[:email] = search_term

    @order = "lower(email) = " +
      ActiveRecord::Base.connection.quote(search_term) +
      " desc, last_name asc"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
    render carts_path
  end
  def new
    @cart = Cart.new
    # binding.pry
    # binding.pry

  end
  def create
    binding.pry
    cart_number = carts_params[:cart_number]
    cart_number_i = cart_number.to_i
    a = Array(1...440383)
    b = Array(320458...383845)
      if a.include?(cart_number_i)
        @cart=Cart.new(carts_params)
      elsif b.include?(cart_number_i)
        @cart=Cart.new(carts_params)
      else
        error_path
      end
    binding.pry
  end
  def search
    @cart = Cart.new
    binding.pry
    cart_number = carts_params[:cart_number]
    a = Array(1...440383)
    b = Array(320458...383845)
      if a.include?(cart_number)
        @cart=Carts.new(carts_params)
      elsif b.include?(cart_number)
        @cart=Carts.new(carts_params)
      else
        error_path
        binding.pry
      end
      error_path
  end

  def show
      @cart = Cart.find(params[:id])
  end

  private
  def carts_params
      params.require(:cart).permit(:id,:cart_number,:number)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  PAGE_SIZE = 10
  def show
    @customer = Customer.find(params[:id])
  end
  def index
    @page = (params[:page] || 0).to_i

    # ...
    if params[:keywords].present?
      @keywords = params[:keywords]
      customer_search_term = CustomerSearchTerm.new(@keywords)
      @customers = Customer.where(
        customer_search_term.where_clause,
        customer_search_term.where_args).
        order(customer_search_term.order).
        offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @customers = []
    end
  end
  def new
    @customer = Customer.new
    binding.pry
  end
  def create
    # binding.pry
    @customer = Customer.new(customer_params)#https://guides.rubyonrails.org/getting_started.html#creating-articles

    if @customer.save
      redirect_to customer_path(@customer)
    else
      render 'new'
    end
  end
private
  def customer_params
    params.require(:customer).permit(:id,:first_name, :last_name, :email,  :phone, :cart_number1, :cart_number2, :cart_number3, :address_number, :address, :city, :state, :zipcode)
      # permitted =  params.require(:customer).permit(:first_name, :last_name, :email,  :phone, :cart_number1, :cart_number2, :cart_number3, :address_number, :address, :city, :state, :zipcode)

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/create.html.erb
<p>
  <h1>Cart Warranty Search Result</h1>
  <h2>
  <% if @cart == nil %>
      Cart is not in Warranty
  <% else%>
     Cart Number: <%=@cart.cart_number%> is in warranty
  <% end%>
  </h2>
</p>
<p><%= link_to "New Cart Search", new_cart_path,  method: :get %></p>
<p><%= link_to "Log Out", destroy_user_session_path,  method: :delete %></p>

app/views/carts/error.html.erb
<p>
  <strong>Cart</strong>
  <h2>
  cart is not the warranty period
  </h2>
</p>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>Number</th>
    <th></th>
  </tr>

  <% @carts.each do |cart| %>
    <tr>
      <td><%= cart.number %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/carts/new.html.erb
<%= form_for @cart do |cart_form| %>
<%= cart_form.text_field :cart_number%>
<%= cart_form.submit "create cart" %>
<!-- binding.pry %>
<% end %>

app/views/carts/search.html.erb
<%= form_for @cart do |cart_form| %>
<%= cart_form.text_field :cart_number%>
<%= cart_form.submit "search cart" %>
<!-- binding.pry %>
<% end %>

app/views/carts/show.html.erb
<p>
  <strong>Cart</strong>
  <h2>
  <%=@cart.number %> is in the warranty period
  </h2>
</p>

app/views/customers/_page.html.erb
<nav>
  <ul>
    <ul class="pager">
      <% if page > 0 %>
      <li class="previous">
        <%=link_to "&larr; Previous".html_safe,
        customers_path(keywords:keywords, page@page -1),
        title: "Previous Page" %>
      </li>
      <% end %>
      <li class= "next">
        <%= link_to "Next &rarr; ".html_safe,
          customers_path(keywords: keywords, page: page +1),
          title: "Next Page" %>
      </li>
  </ul>
</nav>

app/views/customers/index.html.erb
<header>
  <h1 class="h2">Customer Search</h1>
</header>
<% if @custoemrs.present? %>
  <%= render partial: "pager",
  locals: {keywords: @keywords, page: @page} %>
<% end %>
<section class="search-form">
  <%=form_for :customers, method: :get do |f| %>
    <div class="input-group input-group-lg">
      <%= label_tag :keywords, nil, class: "sr-only"%>
      <%= text_field_tag :keywords, nil,
          placeholder: "First Name, Last Name, or Email Address",
          class: "form-control input-lg" %>
      <span class="input-group-btn">
        <%=submit_tag "Find Customers",
                class: "btn btn-primary btn-lg" %>
      </span>
    </div>
  <% end %>
</section>
<section class"search-result">
<header>
  <h1 class="h3">Results</h1>
</header>
<table class="table table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Laste Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>CustomerID</th>
      <th>Joined</th>
    </tr>
  </thead>
  <tbody>
    <%@customers.each do |customer|%>
    <tr>
      <td><%=customer.first_name%></td>
      <td><%=customer.last_name%></td>
      <td><%=customer.email%></td>
      <td><%=customer.address%></td>
      <td><%=customer.customerid%></td>
      <td><%=l customer.created_at.to_date%></td>
    </tr>
    <%end %>
  </tbody>
</table>
<% if @custoemrs.present? %>
  <%= render partial: "pager",
  locals: {keywords: @keywords, page: @page} %>
<% end %>
</section>

app/views/customers/new.html.erb
<%=form_with scope: @customer, url: customers_path, local: true do |form| %>
      <% if @customer.errors.any? %>
       <div id="error_explanation">
        <h2><%= pluralize(customers.errors.count, "error") %> prohibited this customer from being saved:</h2>
          <ul>
          <% customer.errors.full_messages.each do |message| %>
          <li>
            <%=message %>
          </li>
          <% end %>
          </ul>
        </div>
      <% end %>
       <div class="form-row align-items-center">
            <div class="col-aut">
                <%=form.label :first_name %>
                <%=form.text_field :first_name, id: :customer_first_name %>
            </div>

            <div class="col-aut">
                <%=form.label :last_name %>
                <%=form.text_field :last_name, id: :customer_last_name %>
            </div>
            <div class="col-aut">
                <%=form.label :email %>
                <%=form.email_field :email, id: :customer_email %>
            </div>

            <div class="col-aut">
                <%=form.label :phone %>
                <%=form.telephone_field :phone, id: :customer_phone %>
            </div>
            <div class="col-aut">
                  <label>Street Number </label>
                  <%= form.text_field :address_number, id: :customer_address_number %>
            </div>
            <div class="col-aut">
                  <label>Street address </label>
                  <%= form.text_field :address, id: :customer_address %>
            </div>
            <div class="col-aut">
                  <label>City </label>
                  <%= form.text_field :city, id: :customer_city %>
            </div>
            <div class="col-aut">
                  <label>State </label>
                  <%=form.text_field :state, id: :customer_state %>
            </div>

            <div class="col-aut">
                  <label>Zip </label>
                  <%= form.text_field :zipcode, id: :customer_zipcode %>
            </div>
      </div>
      <!-- #### ADDRESS FIELD ENDS HERE #### -->
      <div class="form-row align-items-center">
          <div class="col-sm-2 col-form-label">
              <%=form.label :cart_number1 %>
              <%=form.text_field :cart_number1, id: :customer_cart_number1 %>
          </div>

          <div class="col-sm-2 col-form-label">
              <%=form.label :cart_number2 %>
              <%=form.text_field :cart_number2, id: :customer_cart_number2 %>
          </div>

          <div class="col-sm-2 col-form-label">
              <%=form.label :cart_number3 %>
              <%=form.text_field :cart_number3, id: :customer_cart_number3 %>
          </div>
      </div>
<!-- #### ADDRESS FIELD STARTS HERE #### -->
<div class="actions">
    <%=form.submit 'Submit', class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/customers/show.html.erb
<p>
  <strong>first_name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>last_name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>address_number:</strong>
  <%= @customer.address_number %>
</p>

<p>
  <strong>address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>cart_number1:</strong>
  <%= @customer.cart_number1 %>
</p>

<p>
  <strong>cart_number2:</strong>
  <%= @customer.cart_number2 %>
</p>

<p>
  <strong>cart_number3:</strong>
  <%= @customer.cart_number3 %>
</p>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Welcome to Warranty Claims Program <%= current_user.email %>
  </h1>
  <h2>
    We're using Rails <%= Rails.version %>
  </h2>
</header>
<section>
  <p>
    Future home of Shine's Dashboard
  </p>
      <p><%= link_to "New Customer", new_customer_path,  method: :get %></p>
      <p><%= link_to "New Cart Search", new_cart_path,  method: :get %></p>
      <p><%= link_to "Log Out", destroy_user_session_path,  method: :delete %></p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shine</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <https://getbootstrap.com/docs/4.3/getting-started/introduction> -->
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="container">
      <% if notice.present? %>
        <aside class="alert alert-info">
          <%= notice %>
        </aside>
     <% end %>
     <% if alert.present? %>
       <aside class="alert alert-danger">
         <%= alert %>
       </aside>
    <% end %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>